### ISSUE TITLE
msvcr120.dll is missing in the final JRE distribution for Windows

### ISSUE THREAD

**Issue by qbert1984** [corretto/corretto-8#131]
The final distribution of Corretto 8.212 for Windows (build 1.8.0_212-b04) is missing some dlls in comparison to the Oracle distribution. In particular I need the msvcr120.dll in the jre/bin folder to execute a Windows service installation. Also the msvcp120.dll isn't contained - maybe there are even more.

similar to issue #69

**Comment by EricEdens** [comment]
Thanks for the report -- we'll take a look and get back soon.

**Comment by EricEdens** [comment]
@qbert1984 -- Can you post a minimal reproduction program? It should be a single `.java` file that we can compile and run on our side.

**Comment by qbert1984** [comment]
Hi Eric, I don't know what this should prove. I need the DLL in some way but it is missing - which is a fact. Is there a fundamental problem on including it? Would also be acceptable but maybe you could explain it then... and also why there is a discrepancy regarding DLLs between Corretto and Oracle.

**Comment by TianminShi** [comment]
Hi @qbert1984, just want to let you know we are working on this issue. however I do need a quick anwser from you. which version of Oracle sdk are you using which contains msvcr120.dll ?

**Comment by qbert1984** [comment]
Hi! It was the Oracle JDK 1.8.0_141

**Comment by TianminShi** [comment]
this has been fixed in https://github.com/corretto/corretto-8/releases/tag/8.222.10.3

**Comment by qbert1984** [comment]
Sorry, but I cannot verify this. The dll is still missing in the latest build.

**Comment by TianminShi** [comment]
sorry for not giving enough explaination earlier. here are the reasons I consider this issue closed.

about two years ago (24 Jul 2017) openjfx upgrade their runtime dependencies from VS2013 to VS2017 Which means it depends on a set of new DLLS include (concrt140, vcruntime140, msvcp140) which are the replacement for msvcr120 and msvcp120.  msvcr120 and msvcp120 are no longer dependencies of the latest openjfx, so it does not make sense to include them in Corretto-8. and with the latest release of Corretto-8(https://github.com/corretto/corretto-8/releases/tag/8.222.10.3) we do included the new set of DLLs which are necessary for openjfx to function.

also want to point out that there are not discrepancy between the latest oracle jdk1.8.0_221 and Corretto-8(https://github.com/corretto/corretto-8/releases/tag/8.222.10.3) regarding to vc++ Redistributable. they both don't include msvcr120 and msvcp120. you would have the exactlly same problem if you update to the latest oracle JDK. so if you have other application reqires msvcr120.dll, I think the best ways forward are either bundle it with the application or include it in your installler. hope it helps.

here are two links from openjfx source which point out the difference on runtime dependencies:
latest
http://hg.openjdk.java.net/openjfx/8u/rt/file/tip/modules/graphics/src/main/java/com/sun/javafx/tk/Toolkit.java#l154
older version:
http://hg.openjdk.java.net/openjfx/8u/rt/file/f64b2c61fc25/modules/graphics/src/main/java/com/sun/javafx/tk/Toolkit.java#l147

**Comment by qbert1984** [comment]
Thanks, Tianmin, for the explanation. I'll give it a try
